services:
  ncore-stats:
    build: .
    container_name: ncore-stats
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - data:/app/data
    environment:
      - NICK=${NICK}
      - PASSWORD=${PASS}

volumes:
  data:
